services:
  - type: web
    name: foodhub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn pizza.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pizza.settings
      - key: PYTHON_VERSION
        value: 3.10
